import mongoose from "mongoose";
const EspSchema= new mongoose.Schema({
    ExperimentId:
    {
       type:Number,
       trim:true,
       required:true
    },
    ExperimentName:
    {
       type:String,
       trim:true,
       lowarcase:true,
       required:true
    },
    overview:
    {
       type:String,
       trim:true, 
       required:true
    }, 
    component:{
        type:String,
        trim:true,
       required:true
    },
    pinDiagramInfo:
    {
      type:String,
      trim:true,
       required:true
    },
    CircuitDiagramInfo:
    {
      type:String,
    trim:true,
       required:true
    },
    step1:{
     type:String,
     trim:true,
     lowarcase:true,
     required:true
    },
    step2:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step3:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step4:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step5:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step6:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step7:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step8:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step9:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step10:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step11:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step12:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step13:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step14:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step15:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step16:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step17:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step18:{
        type:String,
        trim:true,
        lowarcase:true,
        required:true
       },
       step19:{
        type:String,
    
       },
       step20:{
        type:String,
       
       },       
    
    code:{
      type:String,
      required:true,
      trim:true
    },
    result:
    {
      type:String,
      trim:true,
      required:true
    },
    image1:{
      type:String,
       required:true
    },
    image2:{
      type:String,
       required:true
    },
    image3:{
      type:String,
       required:true
    },
     
    image4:{
      type:String,
       required:true
    }, 
    image5:{
      type:String,
      
    },
    
      
      
      

})

 

export const Esp=mongoose.models.Esp || mongoose.model("Esp", EspSchema)